apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-tks-usercluster
  namespace: argo
spec:
  entrypoint: deploy
  arguments:
    parameters:
    - name: contract_id
      value: "011b88fa-4d53-439f-9336-67845f994051"
    - name: cluster_id
      value: "67845f99"
    - name: git_account
      value: "tks-management"
    - name: revision
      value: main
    - name: tks_admin
      value: "tks-admin"
    - name: app_name
      value: "tks-cluster"

  templates:
  - name: deploy
    dag:
      tasks:
      - name: tks-create-cluster-site
        template: new-cluster-site
        dependencies: []

      - name: k8s-by-capi
        templateRef:
          name: tks-create-application
          template: AppGroupOnAdmin
        arguments:
          parameters: 
          - name: list
            value: |
              [
                { "path": "cluster-api-aws", "namespace": "argo" }
              ]
        dependencies: [tks-create-cluster-site]

      - name: wait-for-clster-is-registered
        template: wait-template
        dependencies: [k8s-by-capi]

      - name: ready-for-cni-and-csi
        templateRef:
          name: tks-create-application
          template: AppGroup
        arguments:
          parameters: 
          - name: list
            value: |
              [
                { "path": "ingress-nginx", "namespace": "taco-system" },
                { "path": "kubed", "namespace": "taco-system" },
                { "path": "kubernetes-addons", "namespace": "taco-system" }
              ]
        dependencies: [k8s-by-capi, wait-for-clster-is-registered ]

  - name: wait-template
    activeDeadlineSeconds: 1800
    container:
      image: ghcr.io/openinfradev/argocd-cli:v2.0.1
      command:
      - /bin/bash
      - -exc
      - |
        yes | ./argocd login --insecure $ARGO_SERVER --username $ARGO_USERNAME --password $ARGO_PASSWORD

        while [ $(./argocd cluster list | grep \ $target\ | wc -l ) == 0 ]; do
            echo "> Wait for cluster is registered"
            sleep 30
        done
      envFrom:
      - secretRef:
          name: "decapod-argocd-config"
      env:
      - name: target
        value: "{{workflow.parameters.cluster_id}}"

  - name: new-cluster-site
    container:
      # image: golang:1.10
      image: ghcr.io/openinfradev/python_kubectl:v1.0.1
      command:
      - /bin/bash
      - -exc
      - |
        git clone https://$(echo -n $gittoken)@github.com/$git_account/$contract_id.git
        cd $contract_id
        if [ -d $cluster_id ]; then
          echo "Cluster($cluster_id) already exists."
          exit 1
        fi
        cp -r template-site $cluster_id
        sed -i "s/clusterName:\ cluster.local/clusterName:\ $cluster_id/g" $cluster_id/*/site-values.yaml
        git config --global user.email "taco@tacocloud.com"
        git config --global user.name "argo-workflow"
        git add $cluster_id
        git commit -m "new site: $cluster_id"
        git push

        # buffer for starting the github action
        sleep 30

        # waiting for complete of the github action
        echo $gittoken| gh auth login --with-token
        gh run watch $(gh run list --workflow GenerateYaml --limit 1| grep $cluster_id | awk -F push '{print $2}' | awk '{print $1}')

      envFrom:
        - secretRef:
            name: "gittoken"
      env:
        - name: contract_id
          value: "{{workflow.parameters.contract_id}}"
        - name: cluster_id
          value: "{{workflow.parameters.cluster_id}}"
        - name: git_account
          value: "{{workflow.parameters.git_account}}"
        - name: revision
          value: "{{workflow.parameters.revision}}"